### ISSUE TITLE
A question on atomic snapshot logic

### ISSUE THREAD

**Issue by puzpuzpuz** [LPD-EPFL/CLHT#8]
Hello,

I'm considering to port CLHT to Golang and I have a question on the atomic snapshot logic which is present in reads:

```c
	  clht_val_t val = bucket->val[j];
#ifdef __tile__
	  _mm_lfence();
#endif
	  if (bucket->key[j] == key) // Line 1
	    {
	      if (likely(bucket->val[j] == val)) // Line 2
		{
		  return val;
		}
	      else
		{
		  return 0; // Line 3
		}
	    }
```

Let's consider the following scenario. We have three threads doing the following operations:
```
Thread A: |	put(key, val1)	|
Thread B: 			| put(key, val2) |
Thread C: 	|	get(key)	|
--> time
```

It may happen that thread C reads the key and val1 due to Thread A's put outcomes once it's at the Line 1. Then it reads the value at Line 2 and sees val2 since Thread B has started its put. Values don't match and we go into the `else` block returning 0 at the Line 3, while the result should be either val1 (latest finished put) or val2 (concurrent put).

This logic seems wrong to me since get should return the latest (or the previously known) value. If thread C did a previous put for the same key, it'll get 0 instead of the stored value and thus linearizability will be broken. Am I missing something?

**Comment by trigonak** [comment]
Hello.

If I remember correctly, the design is based on the assumption that the `put` operation does not override existing values. Looking at the code:
```c
int
clht_put(clht_t* h, clht_addr_t key, clht_val_t val) 
{
...
 if (bucket->key[j] == key) 
	    {
	      LOCK_RLS(lock);
	      return false;
	    }
...
```
that's indeed the case. Therefore, you cannot get an updated value for the same key; only a delete operation can modify an existing key.

Now, if you would like to change this assumption in your implementation, you can change the `get` protocol from wait-free to lock-free and restart the operation every time that the atomic snapshot fails.

**Comment by puzpuzpuz** [comment]
Yes, I already learned about the put_if_absent semantics and implemented retries on failed atomic snapshot in get in my Golang library. Thanks for the confirmation!

BTW did you evaluate performance with 128B buckets? Intel CPUs have adjacent cache line prefetch default behavior and due to this it's common to see folks using 128B paddings instead of 64B ones to prevent false sharing. So, I'm curious if using 2 CL for buckets changes anything.

**Comment by trigonak** [comment]
Ahh, cool, glad to hear.

As far as I remember I did try with 2 CL bucket, but I don't recall the results to be honest. It does make sense as a configuration though; 6 keys per-bucket should be inexpensive enough to scan when searching, just adding a few extra cycles when a full search of all the keys per bucket happens.

**Comment by puzpuzpuz** [comment]
2 CL should be enough to fit 7 entries. My expectations are that it should improve read latency, since the second half of the bucket is already in (Intel) CPU cache anyway, and also slightly improve writes on NUMA machines where loads of the second cache line may lead to coherence traffic between NUMA nodes (see https://groups.google.com/g/mechanical-sympathy/c/i3-M2uCYTJE).

I'll try to evaluate both options and post an update here.

**Comment by trigonak** [comment]
True, 7 entries. Thanks for the exploration; looking forward to your findings :)

**Comment by puzpuzpuz** [comment]
I tried to use 2 CL bucket size on my laptop (i5-8300H CPU) and only got worse performance. Didn't collect PMU metrics in order to analyze the reason, but so far looks like a bad option to me.

Also, here goes my Golang port of CLHT: https://github.com/puzpuzpuz/xsync/pull/1

It includes a number of modifications described in the PR.

**Comment by trigonak** [comment]
Thanks for sharing. The perf numbers look good :)

Interesting.... I'm positive that I tried the 2CL option back then, and since I didn't inherit it, I expect that I had the same results as you.
